# Generated by Django 3.2.9 on 2021-11-15 07:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c2b1f08e-a12e-4d84-bee3-ae0cb4629817'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8e5ba84c-2eaf-4cbf-9d4b-9ecb26bbdf1a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
